/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Prompt */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Prompt_getLine
    (JNIEnv *env, jobject obj, jstring prompt) {

    char buf[128];
    const jbyte *str;

    str = (*env)->GetStringUTFChars(env, prompt, NULL);
    if (str == NULL) {
        return NULL; /* OutOfMemoryError already thrown */
    }

    printf("%s", str);

    (*env)->ReleaseStringUTFChars(env, prompt, str);

    /* We assume here that the user does not type more than
     * 127 characters */
    scanf("%127s", buf);
    return (*env)->NewStringUTF(env, buf);

}

#ifdef __cplusplus
}
#endif
